name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: |
          mvn test -Dsurefire.suiteXmlFiles=testng.xml
          echo "Listing test-output folder:"
          ls -la test-output || echo "test-output folder not found"

      - name: Compress TestNG Report
        if: always()
        run: |
          if [ -d "test-output" ]; then
            tar -czf testng-report.tar.gz test-output
          else
            echo "test-output folder not found. Skipping compression."
          fi

      - name: Upload TestNG Report Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testng-report
          path: testng-report.tar.gz
